services:
  frontend:
    container_name: tarjans-fe
    build: frontend
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

  backend:
    image: golang:latest
    build: backend
    ports:
      - 8080:8080
    container_name: tarjans-be